# Generated by Django 4.2.16 on 2024-10-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_path',
            field=models.TextField(default='/images/default_avatar.png'),
        ),
    ]
