# Generated by Django 4.2.16 on 2024-10-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_avatar_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_path',
        ),
    ]
