# Generated by Django 4.2.16 on 2024-10-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_is_authenticated'),
        ('authentication', '0005_remove_customuser_avatar_path'),
    ]

    operations = [
    ]
