# Generated by Django 4.2.16 on 2024-10-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_authenticated',
        ),
    ]
