# Generated by Django 4.2.16 on 2024-10-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar_url',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
