# Generated by Django 4.2.16 on 2024-10-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_customuser_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='twofa_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
