# Generated by Django 4.2.16 on 2024-10-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_customuser_avatar_url_customuser_twofa_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='twofa_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
