# Generated by Django 4.2.16 on 2024-10-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_customuser_twofa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enabeld_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
