# Generated by Django 4.2.16 on 2024-10-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_merge_20241013_1412'),
        ('authentication', '0014_customuser_qrcode_path'),
    ]

    operations = [
    ]
